# Generated by Django 5.1.5 on 2025-02-02 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Europe', 'Европа'), ('Africa', 'Африка'), ('Asia', 'Азия'), ('Oceania', 'Океания'), ('North_Central_America', 'Северная и Центральная Америка'), ('South_America', 'Южная Америка')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код языка')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название языка')),
            ],
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('continent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код страны')),
                ('short_name', models.CharField(max_length=100, unique=True, verbose_name='Краткое название страны')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Полное название страны')),
                ('flag', models.URLField(verbose_name='Ссылка на флаг')),
                ('description', models.TextField(verbose_name='Описание страны')),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.federation', verbose_name='Федерация')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='core.language', verbose_name='Основной язык страны')),
            ],
        ),
        migrations.CreateModel(
            name='NationalFirstName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Национальное имя')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_first_names', to='core.language', verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='NationalLastName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Национальная фамилия')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_last_names', to='core.language', verbose_name='Язык')),
            ],
        ),
    ]
